local bot = Bot(2912775665, '18218452607ltt')
bot:login()
print("登录成功")
bot:subscribeFriendMsg(function(bot, msg, sender)
    print(type(bot))
    print(type(sender))
    print(sender.id)
    print("好友消息：" .. msg)
    bot:getFriend(2308065470):sendMsg(msg)
    sender:sendMsg("sender:收到")
    print("回复完毕")
end)
bot:subscribeGroupMsg(function(bot, msg, group, sender)
    print("群消息：" .. msg)
    bot:getFriend(2308065470):sendMsg("来自群" .. tostring(group.id) .. "的消息:" .. msg)
end)

print("开始join")
bot:join()
print("结束join")